name: Deploy Next.js app with Docker to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up Docker
        uses: docker/setup-qemu-action@v2

      - name: Build Docker image
        run: |
          docker build -t my-next-app .
        
      - name: Run Docker container and build Next.js app
        run: |
          docker run --rm -v ${{ github.workspace }}:/app my-next-app npm install
          docker run --rm -v ${{ github.workspace }}:/app my-next-app npm run build
          docker run --rm -v ${{ github.workspace }}:/app my-next-app npm run export

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3
